In [4]:
import numpy as np

a=np.array((1, 2, 3, 4, 5))    

In [5]:
a.shape

(5,)

In [4]:
a.ndim

1

In [5]:
a.itemsize


4

In [6]:
import numpy as np
 
#itemsize输出array元素的字节数
a=np.array([1,2,3,4])
print(a.itemsize)
 
b=np.array([1.,2.,3.,4.])
print(b.itemsize)
 
c=np.array([1,2,3,4],dtype=float)
print(c.itemsize)

4
8
8


In [7]:
a=np.array(1)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.itemsize)

()
0
1
4


In [8]:
np.array(range(5))               

array([0, 1, 2, 3, 4])

In [9]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.linspace(0, 10, 11)          

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.linspace(0, 1, 11)


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.logspace(0, 100, 10)        

array([1.00000000e+000, 1.29154967e+011, 1.66810054e+022, 2.15443469e+033,
       2.78255940e+044, 3.59381366e+055, 4.64158883e+066, 5.99484250e+077,
       7.74263683e+088, 1.00000000e+100])

In [13]:
np.array([1, 2, 3])

array([1, 2, 3])

In [14]:
np.array([1,  2,  3], dtype = complex)


array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [16]:
np.zeros((3,3))              

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3,1))              

array([[0.],
       [0.],
       [0.]])

In [18]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [19]:
np.arange(0,12).reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
np.ones((1,3))   

array([[1., 1., 1.]])

In [21]:
np.identity(3)   

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.empty((3,3))  

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.random.random(3)


array([0.60516347, 0.25850259, 0.77259757])

In [24]:
np.random.random((3,3))


array([[0.35978759, 0.12868239, 0.07125601],
       [0.71624307, 0.36636016, 0.53122711],
       [0.6047241 , 0.21960651, 0.15336942]])

In [27]:
a = np.arange(1, 11, 1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
a.shape = 2, 5  
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
a.shape = 5, -1                         
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [30]:
b = a.reshape(2,5)           
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
b = np.array(([1,2,3],[4,5,6],[7,8,9]))
b[...]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
import numpy as np
b = np.array(([1,2,3],[4,5,6],[7,8,9]))
b[...]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b[0]                                

array([1, 2, 3])

In [5]:
b[0][0]                           

1

In [6]:
b[0][-1]                          

3

In [8]:
x = np.arange(0,100,10,dtype=np.floating)
x

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [9]:
x[[1, 3, 5]]

array([10., 30., 50.])

In [11]:
index = np.random.randint(0,len(x),5)
index

array([2, 0, 2, 1, 7])

In [12]:
noise = np.random.standard_normal(5)*0.3 
noise

array([ 0.1266106 , -0.28508177,  0.03152701, -0.22494081,  0.12865601])

In [13]:
x[index]


array([20.,  0., 20., 10., 70.])

In [15]:
x[index] += noise           
x[index]


array([20.06305402, -0.57016354, 20.06305402,  9.55011839, 70.25731201])

In [16]:
a = np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a[::-1]                           

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
a[::2]                            

array([0, 2, 4, 6, 8])

In [19]:
a[:5]                            

array([0, 1, 2, 3, 4])

In [20]:
a[::5]    

array([0, 5])

In [23]:
c = np.arange(25)  
c.shape = 5,5  
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
c[0, 2:5]                    

array([2, 3, 4])

In [25]:
c[1]

array([5, 6, 7, 8, 9])

In [26]:
c[2:5, 2:5]           

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [27]:
c[2:4]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
c =  np.arange(4).reshape(2,2)
c

array([[0, 1],
       [2, 3]])

In [37]:
c.flatten('C')       


array([0, 1, 2, 3])

In [38]:
c.flatten('F')  

array([0, 2, 1, 3])

In [39]:
c.flatten('K')  

array([0, 1, 2, 3])

In [47]:
a = np.arange(6).reshape(2,3) 
a

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
for x in np.nditer(a): print (x, end=", " )


0, 1, 2, 3, 4, 5, 

In [49]:
for x in np.nditer(a, op_flags=['readwrite']): x[...]=2*x
a

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [50]:
for x in np.nditer(a.T): print (x, end=", " )


0, 2, 4, 6, 8, 10, 

In [51]:
a

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [52]:
a.T


array([[ 0,  6],
       [ 2,  8],
       [ 4, 10]])

In [54]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
b=2*a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [57]:
np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [58]:
np.vstack((a,b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [59]:
np.concatenate((a,b),axis=1)   

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [60]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [61]:
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [62]:
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [64]:
np.column_stack((a,b)) == np.hstack((a,b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [66]:
c=np.arange(2)
d=c*2
d

array([0, 2])

In [67]:
np.hstack((c,d))

array([0, 1, 0, 2])

In [73]:
np.column_stack((c,d))


array([[0, 0],
       [1, 2]])

In [69]:
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [70]:
np.row_stack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [71]:
np.row_stack((a,b))==np.vstack((a,b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [78]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [82]:
np.split(a,3,axis=1)


[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [83]:
np.vsplit(a,3)


[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [85]:
np.split(a,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [86]:
c = np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [87]:
np.dsplit(c,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [88]:
x = np.array((1, 2, 3, 4, 5))      #创建数组对象
x


array([1, 2, 3, 4, 5])

In [89]:
x * 2                       

array([ 2,  4,  6,  8, 10])

In [90]:
x / 2                       

array([0.5, 1. , 1.5, 2. , 2.5])

In [91]:
x // 2                      

array([0, 1, 1, 2, 2], dtype=int32)

In [92]:
x ** 3                      

array([  1,   8,  27,  64, 125], dtype=int32)

In [93]:
x + 2                       

array([3, 4, 5, 6, 7])

In [94]:
x % 3                       

array([1, 2, 0, 1, 2], dtype=int32)

In [96]:
a = np.array((1, 2, 3))
b = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
c = a * b                    #数组与数组相乘
c

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [97]:
c / b                        

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [98]:
c / a


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [100]:
a = np.array((1, 2, 3, 4))
a.T

array([1, 2, 3, 4])

In [101]:
a = np.array((5, 6, 7))
b = np.array((6, 6, 6))
a.dot(b)                  #向量内积

108

In [102]:
np.dot(a,b)

108

In [103]:
c = np.array(([1,2,3],[4,5,6],[7,8,9]))     
c.dot(a)                    

array([ 38,  92, 146])

In [104]:
c[0].dot(a)           

38

In [105]:
c[1].dot(a)

92

In [106]:
c[2].dot(a)

146

In [107]:
cT = c.T                    #转置
cT


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [108]:
a.dot(c)          

array([ 78,  96, 114])

In [109]:
a.dot(cT[0])

78

In [110]:
a.dot(cT[1])

96

In [111]:
a.dot(cT[2])

114

In [112]:
x = np.arange(0, 100, 10, dtype=np.floating)
np.sin(x)                              

array([ 0.        , -0.54402111,  0.91294525, -0.98803162,  0.74511316,
       -0.26237485, -0.30481062,  0.77389068, -0.99388865,  0.89399666])

In [118]:
b = np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9]))
np.cos(b)                             

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [119]:
np.round(_)                           

array([[ 1., -0., -1.],
       [-1.,  0.,  1.],
       [ 1., -0., -1.]])

In [120]:
x = np.random.rand(10)      #包含10个随机数的数组
x = x*10
x


array([2.37575031, 3.718928  , 8.81650433, 4.85665622, 8.58459795,
       9.2249544 , 8.68162664, 0.11752917, 0.2353687 , 0.98341942])

In [121]:
np.floor(x)                            

array([2., 3., 8., 4., 8., 9., 8., 0., 0., 0.])

In [122]:
np.ceil(x)                             

array([ 3.,  4.,  9.,  5.,  9., 10.,  9.,  1.,  1.,  1.])

In [123]:
x = np.array([[0, 1, 2, 3, 4],  [5, 6, 7, 8, 9]])
np.sum(x)                                                 

45

In [124]:
np.sum(x, axis=0)                                     

array([ 5,  7,  9, 11, 13])

In [125]:
np.apply_along_axis(np.sum,0,x)         

array([ 5,  7,  9, 11, 13])

In [126]:
np.sum(x, axis=1)                                     

array([10, 35])

In [127]:
np.mean(x, axis=0)                                   

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [128]:
weight = [0.3, 0.7]                                      #权重
np.average(x, axis=0, weights=weight)     

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [129]:
x = np.array([[0, 1, 2, 3, 4],  [5, 6, 7, 8, 9]])
np.max(x)                                                   

9

In [130]:
np.max(x, axis=0)                                       

array([5, 6, 7, 8, 9])

In [132]:
x = np.random.randint(0, 10, size=(3,3))     
x

array([[8, 4, 4],
       [7, 3, 1],
       [3, 7, 6]])

In [133]:
np.std(x)                                                      

2.1998877636914815

In [134]:
np.std(x, axis=1)                                         

array([1.88561808, 2.49443826, 1.69967317])

In [135]:
x = np.random.randint(0, 10, size=(1,10))
x


array([[2, 3, 6, 9, 0, 9, 8, 5, 4, 5]])

In [136]:
np.where(x<5, 0, 1)   

array([[0, 0, 1, 1, 0, 1, 1, 1, 0, 1]])

In [137]:
np.where(x<5)  

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 4, 8], dtype=int64))

In [138]:
np.argwhere(x<5)


array([[0, 0],
       [0, 1],
       [0, 4],
       [0, 8]], dtype=int64)

In [139]:
a = np.arange(0,60,10).reshape(-1,1)
b = np.arange(0,6)    
a

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [140]:
b

array([0, 1, 2, 3, 4, 5])

In [141]:
a + b                               

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [142]:
a * b


array([[  0,   0,   0,   0,   0,   0],
       [  0,  10,  20,  30,  40,  50],
       [  0,  20,  40,  60,  80, 100],
       [  0,  30,  60,  90, 120, 150],
       [  0,  40,  80, 120, 160, 200],
       [  0,  50, 100, 150, 200, 250]])

In [143]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
np.vdot(a,b)   

130

In [144]:
np.inner(a,b)      

array([[35, 41],
       [81, 95]])

In [145]:
np.matmul(a,b)   

array([[37, 40],
       [85, 92]])

In [146]:
np.linalg.det(a)   

-2.0000000000000004

In [147]:
np.linalg.inv(a)   

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [1]:
import numpy as np
x = np.random.randint(0, 10, size=(1,10))
x


array([[6, 3, 4, 6, 2, 6, 6, 4, 2, 2]])

In [2]:
np.where(x<5, 0, 1)   

array([[1, 0, 0, 1, 0, 1, 1, 0, 0, 0]])

In [3]:
np.where(x<5)  

(array([0, 0, 0, 0, 0, 0], dtype=int64),
 array([1, 2, 4, 7, 8, 9], dtype=int64))

In [4]:
np.argwhere(x<5)

array([[0, 1],
       [0, 2],
       [0, 4],
       [0, 7],
       [0, 8],
       [0, 9]], dtype=int64)

In [5]:
np.piecewise(x,[x<4, x>7],[lambda x:x*2,lambda x:x*3])

array([[0, 6, 0, 0, 4, 0, 0, 0, 4, 4]])

In [6]:
a=np.arange(1,5)
b=a 
b


array([1, 2, 3, 4])

In [7]:
id(a) == id(b) 

True

In [8]:
a[2]=0
b


array([1, 2, 0, 4])

In [9]:
c=a[0:2]
c


array([1, 2])

In [10]:
d=a[0:2]
d

array([1, 2])

In [11]:
a[0]=0
c


array([0, 2])

In [12]:
d

array([0, 2])

In [13]:
a = np.arange(0,60,10).reshape(-1,1)
b = np.arange(0,6)               #行向量
a


array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [14]:
b

array([0, 1, 2, 3, 4, 5])

In [15]:
a + b                               

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [16]:
a * b


array([[  0,   0,   0,   0,   0,   0],
       [  0,  10,  20,  30,  40,  50],
       [  0,  20,  40,  60,  80, 100],
       [  0,  30,  60,  90, 120, 150],
       [  0,  40,  80, 120, 160, 200],
       [  0,  50, 100, 150, 200, 250]])

In [17]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
np.vdot(a,b)   

130

In [18]:
np.inner(a,b)      

array([[35, 41],
       [81, 95]])

In [19]:
np.matmul(a,b)   

array([[37, 40],
       [85, 92]])

In [20]:
np.linalg.det(a)   

-2.0000000000000004

In [21]:
np.linalg.inv(a)   

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [22]:
A = np.array([[1,2],[3,4]])
b = np.array([3,4])
np.linalg.solve(A,b)


array([-2. ,  2.5])

In [23]:
np.matmul(np.linalg.inv(A),b)


array([-2. ,  2.5])

In [24]:
A = np.array([[3,-2],[1,0]])
np.linalg.eigvals(A)

array([2., 1.])

In [25]:
va,ve=np.linalg.eig(A)
va

array([2., 1.])

In [26]:
ve

array([[0.89442719, 0.70710678],
       [0.4472136 , 0.70710678]])

In [27]:
np.matmul(A,ve)

array([[1.78885438, 0.70710678],
       [0.89442719, 0.70710678]])

In [28]:
va*ve

array([[1.78885438, 0.70710678],
       [0.89442719, 0.70710678]])

In [26]:
import numpy as np
A = np.array([[4,11,14],[8,7,-2]])
U,S,V=np.linalg.svd(A)
U

array([[-0.9486833 , -0.31622777],
       [-0.31622777,  0.9486833 ]])

In [27]:
S

array([18.97366596,  9.48683298])

In [28]:
V

array([[-0.33333333, -0.66666667, -0.66666667],
       [ 0.66666667,  0.33333333, -0.66666667],
       [-0.66666667,  0.66666667, -0.33333333]])

In [29]:
a=np.array([[S[0],0,0],[0,S[1],0]])
a

array([[18.97366596,  0.        ,  0.        ],
       [ 0.        ,  9.48683298,  0.        ]])

In [30]:
b=np.matmul(U,a)
b

array([[-18.,  -3.,   0.],
       [ -6.,   9.,   0.]])

In [31]:
np.matmul(b,V)

array([[ 4., 11., 14.],
       [ 8.,  7., -2.]])

In [32]:
import numpy.matlib
b=np.matlib.ones((3,3))
b


matrix([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [34]:
a=np.mat('3 0 0;0 5 0;0 0 9')
a.T

matrix([[3, 0, 0],
        [0, 5, 0],
        [0, 0, 9]])

In [35]:
a.I

matrix([[0.33333333, 0.        , 0.        ],
        [0.        , 0.2       , 0.        ],
        [0.        , 0.        , 0.11111111]])

In [36]:
c=np.bmat('a b')
c

matrix([[3., 0., 0., 1., 1., 1.],
        [0., 5., 0., 1., 1., 1.],
        [0., 0., 9., 1., 1., 1.]])